version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 9020:8000
    volumes:
      - /mnt/10tb/docker/youtube/download:/youtube
      - /mnt/10tb/docker/youtube/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=${LOCAL_SITE}        # set your host name
      - TA_USERNAME=${USER}           # your initial TA credentials
      - TA_PASSWORD=${TA_PASS}              # your initial TA credentials
      - ELASTIC_PASSWORD=${ELASTIC_PASS}         # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
#      - TA_PORT=9020
#      - TA_UWSGI_PORT=9030
    networks:
      - proxy
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson                 # for arm64 use bbilly1/rejson
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - proxy
    volumes:
      - ./data/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.5.1
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASS}       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    networks:
      - proxy
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/10tb/docker/youtube/es/snapshot:/usr/share/elasticsearch/data/snapshot
      - /mnt/10tb/docker/youtube/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
  
networks:
  proxy:
    external: true

