version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    networks:
      - proxy
    volumes:
      - ./config:/config
    ports:
      - 8052:80
      - 8453:443
    restart: unless-stopped

networks:
  proxy:
    external: true
