---
version: "3.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
#      - PASSWORD=password #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
#      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
    ports:
      # This is a HTTP port (not HTTPS) this confused me at first
      - 8442:8443
    restart: unless-stopped

networks:
  proxy:
    external: true
