version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
#    command: --skip-innodb-read-only-compressed
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - TZ=America/New_York
#      - MYSQL_DATABASE=USER_DB_NAME #optional
#      - MYSQL_USER=MYSQL_USER #optional
#      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
#      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    networks:
      - proxy
    volumes:
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    restart: unless-stopped

networks:
  proxy:
    external: true
