version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    networks:
      - proxy
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${redis_password}
    volumes: 
      - ./data:/data

networks:
  proxy:
    external: true
